# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=255, unique=True)),
                ('automatic', models.BooleanField(default=False)),
                ('insured', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
